apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: mstdpostextract
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 3
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 6000
  idletimeout: 120
  package:
    functionName: mstdpostextract.main
    packageref:
      name: mstdpostextract
      namespace: ""
  requestsPerPod: 1
  resources: {}
